version: '3'
services:
  node-docker-mern-container:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000


  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dotOnline
      - MONGO_INITDB_ROOT_PASSWORD=dotonline
    volumes:
      - mongo-db:/data/db


volumes:
  mongo-db: