version: "3"
services:
  node-docker-mern-container:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dotOnline
      - MONGO_INITDB_ROOT_PASSWORD=dotonline
